name: rentisha_kodi_flutter
description: A new Flutter project.
publish_to: 'none' # Remove this line if you want to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  google_maps_flutter: ^2.5.0
  provider: ^6.1.2
  flutter_form_builder: ^9.2.0
  image_picker: ^1.0.7
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.2
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

